name: misalon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4  # Para base de datos
  http: ^1.1.0
  html: ^0.15.4  # Para parsing HTML m√°s robusto
  excel: ^4.0.3  # Para generar archivos Excel
  file_picker: ^8.1.2  # Para seleccionar archivos
  path_provider: ^2.1.4  # Para rutas de archivos
  permission_handler: ^11.3.1  # Para permisos de almacenamiento

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
